// src/core/middlewares/response-wrapper.middleware.ts
import type { Request, Response, NextFunction } from 'express';

/**
 * Interface defining the standard structure for API responses.
 * Ensures consistency across all successful and failed service outputs.
 */
interface ServiceResponseBody {
  success: boolean;
  message: string;
  data?: unknown;
  requestId?: string;
  [key: string]: unknown; // Allows for additional dynamic properties
}

/**
 * Middleware that intercepts the 'res.json' method to automatically
 * inject the unique Request ID into every outgoing API response.
 * * This facilitates frontend-backend correlation for debugging
 * and log tracing.
 */
export const responseWrapperMiddleware = (
  req: Request,
  res: Response,
  next: NextFunction,
): void => {
  // Capture the original 'res.json' function to extend its behavior
  const originalJson = res.json;

  /**
   * Overwrite the default 'res.json' method.
   * We use a traditional function instead of an arrow function to preserve
   * the 'this' context of the Express Response object.
   */
  res.json = function (body: unknown): Response {
    // Check if the response body is a valid object before modifying
    if (body && typeof body === 'object' && body !== null) {
      // Create a shallow copy to avoid mutating the original data source
      const responseBody = { ...body } as ServiceResponseBody;

      // Inject the requestId if it was previously generated by the requestIdMiddleware
      if (!responseBody.requestId && req.id) {
        responseBody.requestId = req.id;
      }

      // Execute the original json method with the modified payload
      return originalJson.call(this, responseBody);
    }

    // If the body is not an object (e.g., a string or null), return it as is
    return originalJson.call(this, body);
  };

  next();
};
